<!-- ...................................................................... -->
<!-- Markup Language for IETF RFC Additional vocabularies used in rfc2629.xslt : 'ed'
             Common Attributes Module ..................................... -->
<!-- file: ed-attribs.mod
     

     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/ed-attribs.mod"
     
     ...................................................................... -->

<!-- Common Attributes

     This module declares many of the common attributes.
-->

<!ENTITY % ed.common.extra.attrib "">

<!ENTITY % ed.formatTitle.attrib
	"who	CDATA	#IMPLIED
	datetime	CDATA	#IMPLIED
	reason	CDATA	#IMPLIED
	cite	CDATA	#IMPLIED">

<!ENTITY % ed.common.attrib
	"%ed.common.extra.attrib;
	%ed.xmlns.attrib;">


<!-- end of ed-attribs.mod -->
