<!-- ...................................................................... -->
<!-- Markup Language for IETF RFC Additional vocabularies used in rfc2629.xslt : 'ed'
             Hyperlink Module ............................................. -->
<!-- file: myns-hyperlink.mod
     

     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:42:58+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/myns-hyperlink.mod"
     
     ...................................................................... -->

<!-- Hyperlink

       link
-->

<!-- link: = XHTML1:link ............................... -->

<!ENTITY % myns.link.element "INCLUDE">
<![%myns.link.element;[
<!ENTITY % myns.link.content "EMPTY">
<!ENTITY % myns.link.qname "link">
<!ENTITY % myns.link.tagmin.start "-">
<!ENTITY % myns.link.tagmin.end "o">
<![%sgml.tag.minimizable;[
<!ENTITY % myns.link.tagmin "%myns.link.tagmin.start; %myns.link.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % myns.link.tagmin "">
<!ELEMENT %myns.link.qname; %myns.link.tagmin; %myns.link.content;>
<!-- end of myns.link.element -->]]>

<!ENTITY % myns.link.attlist "INCLUDE">
<![%myns.link.attlist;[
<!ATTLIST %myns.link.qname;
	href	%URI.datatype;	#REQUIRED
	rel	%LinkTypes.datatype;	#IMPLIED
	title	CDATA	#IMPLIED
	%myns.common.attrib;>
<!-- end of myns.link.attlist -->]]>


<!-- end of myns-hyperlink.mod -->
