<!-- ...................................................................... -->
<!-- Draft revision of RFC 2629 <http://xml.resource.org/authoring/draft-mrose-writing-rfcs.html>
             Inline Module ................................................ -->
<!-- file: rfc2629bis-inline.mod
     

     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/rfc2629bis-inline.mod"
     
     ...................................................................... -->

<!-- Inline

       spanx
-->

<!-- spanx: Provide formatting guidance to the XML application  -->

<!ENTITY % rfc2629bis.spanx.element "INCLUDE">
<![%rfc2629bis.spanx.element;[
<!ENTITY % rfc2629bis.spanx.content "(%rfc2629.CTEXT.datatype;)">
<!ENTITY % rfc2629bis.spanx.qname "spanx">
<!ENTITY % rfc2629bis.spanx.tagmin.start "-">
<!ENTITY % rfc2629bis.spanx.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % rfc2629bis.spanx.tagmin "%rfc2629bis.spanx.tagmin.start; %rfc2629bis.spanx.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % rfc2629bis.spanx.tagmin "">
<!ELEMENT %rfc2629bis.spanx.qname; %rfc2629bis.spanx.tagmin; %rfc2629bis.spanx.content;>
<!-- end of rfc2629bis.spanx.element -->]]>

<!ENTITY % rfc2629bis.spanx.attlist "INCLUDE">
<![%rfc2629bis.spanx.attlist;[
<!ATTLIST %rfc2629bis.spanx.qname;
	style	%rfc2629bis.spanx-style.datatype;	"emph"
	%rfc2629bis.common.attrib;>
<!-- end of rfc2629bis.spanx.attlist -->]]>


<!-- end of rfc2629bis-inline.mod -->
