<!-- ...................................................................... -->
<!-- Draft revision of RFC 2629 <http://xml.resource.org/authoring/draft-mrose-writing-rfcs.html>
             Common Attributes Module ..................................... -->
<!-- file: rfc2629bis-attribs.mod
     

     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/rfc2629bis-attribs.mod"
     
     ...................................................................... -->

<!-- Common Attributes

     This module declares many of the common attributes.
-->

<!ENTITY % rfc2629bis.common.extra.attrib "">

<!ENTITY % rfc2629.anchor.attrib
	"anchor	ID	#IMPLIED">

<!ENTITY % rfc2629.section-title.attrib
	"title	%rfc2629bis.ATEXT.datatype;	#REQUIRED">

<!ENTITY % rfc2629bis.common.attrib
	"%rfc2629bis.common.extra.attrib;
	%rfc2629bis.xmlns.attrib;">


<!-- end of rfc2629bis-attribs.mod -->
