<!-- ...................................................................... -->
<!-- Japanese Translation Markup Framework for RFC 2629 Markups
             Figure Module ................................................ -->
<!-- file: rfc2629ja-figure.mod
     
     This is an additional markup vocabulary to support RFC translations.
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/rfc2629ja-figure.mod"
     
     ...................................................................... -->

<!-- Figure

       artwork
-->

<![%rfc2629ja.rfc2629.module;[
<!ENTITY % rfc2629ja.artwork.content "((%rfc2629.artwork.qname;,(%Block.class;)?)|%Block.class;)">
<!-- end of rfc2629ja.rfc2629 -->]]>

<!-- artwork: Wrapper element for a rfc2629:artwork (preformatted ASCII text)
     and/or something an XML block level element  -->

<!ENTITY % rfc2629ja.artwork.element "INCLUDE">
<![%rfc2629ja.artwork.element;[
<!ENTITY % rfc2629ja.artwork.content "(%Block.class;)">
<!ENTITY % rfc2629ja.artwork.qname "artwork">
<!ENTITY % rfc2629ja.artwork.tagmin.start "-">
<!ENTITY % rfc2629ja.artwork.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % rfc2629ja.artwork.tagmin "%rfc2629ja.artwork.tagmin.start; %rfc2629ja.artwork.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % rfc2629ja.artwork.tagmin "">
<!ELEMENT %rfc2629ja.artwork.qname; %rfc2629ja.artwork.tagmin; %rfc2629ja.artwork.content;>
<!-- end of rfc2629ja.artwork.element -->]]>

<!ENTITY % rfc2629ja.artwork.attlist "INCLUDE">
<![%rfc2629ja.artwork.attlist;[
<!ATTLIST %rfc2629ja.artwork.qname;
	%rfc2629ja.common.attrib;>
<!-- end of rfc2629ja.artwork.attlist -->]]>


<!-- end of rfc2629ja-figure.mod -->
