<!-- ...................................................................... -->
<!-- Japanese Translation Markup Framework for RFC 2629 Markups
             Datatypes Module ............................................. -->
<!-- file: rfc2629ja-datatype.mod
     
     This is an additional markup vocabulary to support RFC translations.
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/rfc2629ja-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- [0-9]+ -->
<!ENTITY % rfc2629.NUMBER.datatype "NMTOKEN">

<!-- URI Reference -->
<!ENTITY % URI.datatype "CDATA">

<!-- "1" / "2" / ... / "31" -->
<!ENTITY % rfc2629.DAY.datatype "NMTOKEN">

<!ENTITY % rfc2629ja.month.datatype "(01|02|03|04|05|06|07|08|09|10|11|12)">

<!-- 4DIGIT -->
<!ENTITY % rfc2629.YEAR.datatype "NMTOKEN">

<!-- *CHAR (content of mixed context element) -->
<!ENTITY % rfc2629.TEXT.datatype "#PCDATA">


<!-- end of rfc2629ja-datatype.mod -->
