<!-- ...................................................................... -->
<!-- Draft revision of RFC 2629 <http://xml.resource.org/authoring/draft-mrose-writing-rfcs.html>
             Datatypes Module ............................................. -->
<!-- file: rfc2629bis-datatype.mod
     

     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/rfc2629bis-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.

     Note: This module should be included before rfc2629-datatype.mod
     is included, since some definition is updated.
-->

<!ENTITY % rfc2629.ATEXT.datatype "CDATA">

<!ENTITY % rfc2629.CTEXT.datatype "#PCDATA">

<!-- 'TXT' / ... -->
<!ENTITY % rfc2629bis.format-type.datatype "CDATA">

<!-- $formatting-string -->
<!ENTITY % rfc2629bis.list-counter.datatype "CDATA">

<!-- IETF Language Code -->
<!ENTITY % LanguageCode.datatype "CDATA">

<!-- (numbers|symbols|hanging|empty|$format)
     
     $format    := 'format ' $formatting-string
     $formatting-string := $bare $percented $bare
     $bare      := $CDATA - ([$CDATA] $percented [$CDATA])
     $percented := '%d' / '%c' -->
<!ENTITY % rfc2629.list-style.datatype "CDATA">

<!-- 1*DIGIT -->
<!ENTITY % rfc2629.NUMBER.datatype "NMTOKEN">

<!-- 1*DIGIT "%" -->
<!ENTITY % rfc2629bis.percentage.datatype "CDATA">

<!-- Author's role -->
<!ENTITY % rfc2629bis.role.datatype "(editor)">

<!ENTITY % rfc2629.truefalse.datatype "(true|false)">

<!-- URI Reference -->
<!ENTITY % URI.datatype "CDATA">

<!-- (emph|strong|verb|$ext) -->
<!ENTITY % rfc2629bis.xspan-style.datatype "CDATA">


<!-- end of rfc2629bis-datatype.mod -->
