<!-- ...................................................................... -->
<!-- Draft revision of RFC 2629 <http://xml.resource.org/authoring/draft-mrose-writing-rfcs.html>
             Document Structure Module .................................... -->
<!-- file: rfc2629bis-struct.mod
     

     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/rfc2629bis-struct.mod"
     
     ...................................................................... -->

<!-- Document Structure

       appendix

     This module defines the major structural element types and
     their attributes.
-->

<![%rfc2629bis.rfc2629.module;[
<!ENTITY % rfc2629bis.list.add.attlist "INCLUDE">
<![%rfc2629bis.list.add.attlist;[
<!ATTLIST %rfc2629.list.qname;
	counter	%rfc2629bis.list-counter.datatype;	#IMPLIED
	hangIndent	%rfc2629.NUMBER.datatype;	#IMPLIED>
<!-- end of rfc2629bis.list.add.attlist -->]]>

<!-- end of rfc2629bis.rfc2629 -->]]>

<!-- appendix: An appendix section of the document ..... -->

<!ENTITY % rfc2629bis.appendix.element "INCLUDE">
<![%rfc2629bis.appendix.element;[
<!ENTITY % rfc2629bis.appendix.content "(%Block.mix;)*">
<!ENTITY % rfc2629bis.appendix.qname "appendix">
<!ENTITY % rfc2629bis.appendix.tagmin.start "-">
<!ENTITY % rfc2629bis.appendix.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % rfc2629bis.appendix.tagmin "%rfc2629bis.appendix.tagmin.start; %rfc2629bis.appendix.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % rfc2629bis.appendix.tagmin "">
<!ELEMENT %rfc2629bis.appendix.qname; %rfc2629bis.appendix.tagmin; %rfc2629bis.appendix.content;>
<!-- end of rfc2629bis.appendix.element -->]]>

<!ENTITY % rfc2629bis.appendix.attlist "INCLUDE">
<![%rfc2629bis.appendix.attlist;[
<!ATTLIST %rfc2629bis.appendix.qname;
	%rfc2629.anchor.attrib;
	%rfc2629.section-title.attrib;
	%rfc2629bis.common.attrib;>
<!-- end of rfc2629bis.appendix.attlist -->]]>


<!-- end of rfc2629bis-struct.mod -->
