<!-- ...................................................................... -->
<!-- Draft revision of RFC 2629 <http://xml.resource.org/authoring/draft-mrose-writing-rfcs.html>
             QName (Qualified Name) Module ................................ -->
<!-- file: rfc2629bis-qname.mod
     

     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/rfc2629bis-qname.mod"
     
     ...................................................................... -->

<!-- Draft revision of RFC 2629 QName (Qualified Name) Module

     This module is contained in two parts, labeled Section 'A' and 'B':
     
       Section A declares parameter entities to support namespace-qualified
       names, namespace declarations, and name prefixing.
     
       Section B declares parameter entities used to provide namespace-qualified
       names for all element types and global attribute names.
-->

<!ENTITY % sgml.tag.minimizable "IGNORE">

<!ENTITY % NS.prefixed "IGNORE">

<!-- Section A: XML Namespace Framework :::::::::::::::::::::::::: -->

<!-- 1. Declare a %rfc2629bis.prefixed; conditional section keyword, used
        to activate namespace prefixing. -->
<!ENTITY % rfc2629bis.prefixed "IGNORE">

<!ENTITY % rfc2629bis.global.attrs.prefixed "IGNORE">

<!ENTITY % rfc2629bis.xsi.attrs "INCLUDE">

<!-- 2. Declare a parameter entity %rfc2629bis.xmlns; containing
        the URI reference used to identity the namespace. -->
<!ENTITY % rfc2629bis.xmlns "urn:x-suika-fam-cx:markup:ietf:rfc:2629:">

<!-- 3. Declare parameter entity %rfc2629bis.prefix; containing
        the default namespace prefix string to use when prefixing
        is enabled. This may be overridden in the DTD driver or the
        internal subset of a document instance.
        
        NOTE: As specified in XML Namespace speficications, the namespace
        prefix serves as a proxy for the URI reference, and is not in itself
        significant. -->
<!ENTITY % rfc2629bis.prefix "rfc">

<!-- 4. Declare parameter entity %rfc2629bis.pfx; containing the
        colonized prefix (e.g, '%rfc2629bis.prefix;:') used when
        prefixing is active, an empty string when it is not. -->
<![%rfc2629bis.prefixed;[
<!ENTITY % rfc2629bis.pfx "%rfc2629bis.prefix;:">
]]>
<!ENTITY % rfc2629bis.pfx "">

<!-- declare qualified name extensions here ............ -->
<!ENTITY % rfc2629bis-qname-extra.mod "">
%rfc2629bis-qname-extra.mod;

<!-- 5. The parameter entity %rfc2629bis.xmlns.extra.attrib; may be
        redeclared to contain any foreign namespace declaration
        attributes for namespaces embedded.  The default
        is an empty string. -->
<!ENTITY % rfc2629bis.xmlns.extra.attrib "">

<!-- The parameter entity %URI.datatype; should already be defined in
     Datatype module. -->
<!ENTITY % URI.datatype "CDATA">

<![%rfc2629bis.prefixed;[
<!ENTITY % rfc2629bis.xmlns.decl.attrib
	"xmlns:%rfc2629bis.prefix;	%URI.datatype;	#FIXED '%rfc2629bis.xmlns;'">
]]>
<!ENTITY % rfc2629bis.xmlns.decl.attrib
	"xmlns	%URI.datatype;	#FIXED '%rfc2629bis.xmlns;'">

<!-- Declare a parameter entity %XSI.prefix as a prefix to use for
     XML Schema Instance attributes. -->
<!ENTITY % XSI.prefix "xsi">

<!ENTITY % XSI.pfx "%XSI.prefix;:">

<!ENTITY % XSI.xmlns "http://www.w3.org/2001/XMLSchema-instance">

<!-- Declare a parameter entity %XSI.xmlns.attrib as support for
     the schemaLocation attribute. -->
<!ENTITY % XSI.xmlns.attrib
	"xmlns:%XSI.prefix;	%URI.datatype;	#FIXED '%XSI.xmlns;'">

<![%rfc2629bis.prefixed;[
<!ENTITY % NS.decl.attrib
	"%rfc2629bis.xmlns.decl.attrib;
	%rfc2629bis.xmlns.extra.attrib;
	%XSI.xmlns.attrib;">
]]>
<!ENTITY % NS.decl.attrib
	"%rfc2629bis.xmlns.extra.attrib;
	%XSI.xmlns.attrib;">

<!-- Declare a parameter entity containing all XML namespace declaration
     attributes used, including a default xmlns declaration when prefixing
     is inactive. -->
<![%rfc2629bis.prefixed;[
<!ENTITY % rfc2629bis.xmlns.attrib
	"%NS.decl.attrib;">
]]>
<!ENTITY % rfc2629bis.xmlns.attrib
	"%rfc2629bis.xmlns.decl.attrib;
	%NS.decl.attrib;">

<!-- Section B: Draft revision of RFC 2629 Qualified Names :::::::: -->

<!-- placeholder for qualified name redeclarations -->
<!ENTITY % rfc2629bis-qname.redecl "">
%rfc2629bis-qname.redecl;

<!-- 6. This section declare parameter entities used to provide
        namespace-qualified names for all element types and global
        attribute names. -->
<!ENTITY % rfc2629bis.annotation.qname "%rfc2629bis.pfx;annotation">
<!ENTITY % rfc2629bis.appendix.qname "%rfc2629bis.pfx;appendix">
<!ENTITY % rfc2629bis.c.qname        "%rfc2629bis.pfx;c">
<!ENTITY % rfc2629bis.format.qname   "%rfc2629bis.pfx;format">
<!ENTITY % rfc2629bis.spanx.qname    "%rfc2629bis.pfx;spanx">
<!ENTITY % rfc2629bis.texttable.qname "%rfc2629bis.pfx;texttable">
<!ENTITY % rfc2629bis.ttcol.qname    "%rfc2629bis.pfx;ttcol">

<!ENTITY % rfc2629bis.role.attrib.qname "%rfc2629bis.prefix;:role">


<!-- end of rfc2629bis-qname.mod -->
