<!-- ...................................................................... -->
<!-- Markup Language for IETF RFCs (RFC 2629) Datatypes Module ............ -->
<!-- file: rfc2629-datatype.mod
     
     This is a XML based markup language for IETF RFC documents.
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/2629/rfc2629-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- [0-9]+ -->
<!ENTITY % rfc2629.NUMBER.datatype "CDATA">

<!-- [NUMBER *("," NUMBER)] -->
<!ENTITY % rfc2629.NUMBERS.datatype "CDATA">

<!-- "1" / "2" / ... / "31" -->
<!ENTITY % rfc2629.DAY.datatype "CDATA">

<!-- 'January' / 'February' / ... / 'December' -->
<!ENTITY % rfc2629.MONTH.datatype "CDATA">

<!-- 4DIGIT -->
<!ENTITY % rfc2629.YEAR.datatype "CDATA">

<!-- URI Reference -->
<!ENTITY % URI.datatype "CDATA">

<!-- [U+0020-U+007E]+ (attribute value) -->
<!ENTITY % rfc2629.ATEXT.datatype "CDATA">

<!-- [U+0020-U+007E]+ (content of element) -->
<!ENTITY % rfc2629.CTEXT.datatype "#PCDATA">

<!-- *CHAR (content of mixed context element) -->
<!ENTITY % rfc2629.TEXT.datatype "#PCDATA">

<!-- should be a two-letter code from ISO 3166 -->
<!ENTITY % rfc2629.country.datatype "#PCDATA">

<!ENTITY % rfc2629.list-style.datatype "CDATA">

<!-- 'RFC' / ... -->
<!ENTITY % rfc2629.series-name.datatype "CDATA">

<!ENTITY % rfc2629.truefalse.datatype "(true|false)">


<!-- end of rfc2629-datatype.mod -->
