<!-- ...................................................................... -->
<!-- Japanese Translation Markup Framework for RFC 2629 Markups
             notation Module .............................................. -->
<!-- file: rfc2629ja-notation.mod
     
     This is an additional markup vocabulary to support RFC translations.
     
     Copyright 2010 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2010-06-20T04:43:53+00:00 (Generated by mkdtds/1.7)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/gate/cvs/*checkout*/markup/rfc/dtd/module/rfc2629ja-notation.mod"
     
     ...................................................................... -->

<!-- notation


-->

<!-- <?rfc-translation?> processing instruction -->
<!NOTATION rfc-translation SYSTEM "urn:x-suika-fam-cx:markup:rfc:translation:pi">


<!-- end of rfc2629ja-notation.mod -->
